apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

resources:
  - ../../base
patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: database-patch.yaml
